/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.edu.utp.ciclo2reto5.view;

import com.edu.utp.ciclo2reto5.controller.InformesController;
import com.edu.utp.ciclo2reto5.model.vo.ComprasProveedorVo;
import com.edu.utp.ciclo2reto5.model.vo.LiderVo;
import com.edu.utp.ciclo2reto5.model.vo.ProyectoVo;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;

/**
 *
 * @author NORBERTO AGUDELO
 */
public class VistaInformesReto4 extends javax.swing.JFrame {

    /**
     * Creates new form VistaInformesReto4
     */
    private static InformesController controller;
    
    JTable jTableConsultas;

    public VistaInformesReto4() {
        controller = new InformesController();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPaneConsultas = new javax.swing.JScrollPane();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButton1.setText("Informe 1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Infome 2");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Informe 3");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Borrar Infome");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(255, 0, 51));
        jLabel1.setText("Consultas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPaneConsultas, javax.swing.GroupLayout.DEFAULT_SIZE, 607, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addComponent(jButton1)
                                .addGap(61, 61, 61)
                                .addComponent(jButton2)
                                .addGap(44, 44, 44)
                                .addComponent(jButton3)
                                .addGap(42, 42, 42)
                                .addComponent(jButton4))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(237, 237, 237)
                                .addComponent(jLabel1)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPaneConsultas, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addComponent(jButton4))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jScrollPaneConsultas.setViewportView(null);
        jLabel1.setText("Consultas");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:        
        System.out.println("Informe1");
        jLabel1.setText("Lider por Ciudad");

        try {
            List<LiderVo> lideres = controller.listarLideres();
            for (LiderVo lider : lideres) {
                System.out.println(lider);
            }
        } catch (Exception ex) {
            System.err.println("Error: " + ex);
            ex.printStackTrace();
        }
        try {
            construirTablaLider();
        } catch (SQLException ex) {
            Logger.getLogger(VistaInformesReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Proyectos de Casa Campestre");
        try {
            construirTablaProyectos();
        } catch (SQLException ex) {
            Logger.getLogger(VistaInformesReto4.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jLabel1.setText("Lider por Ciudad");
        try {
            construirTablaComprasProveedor();
        } catch (SQLException ex) {
            Logger.getLogger(VistaInformesReto4.class.getName()).log(Level.SEVERE, null, ex);
        }        
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void construirTablaLider() throws SQLException {
        String titulos[] = {"ID_Lider", "Nombre", "Primer_Apellido", "Ciudad_Residencia"};
        String informacionLider[][] = obtenerMatrizLider();        
        jTableConsultas = new JTable(informacionLider,titulos);
        jScrollPaneConsultas.setViewportView(jTableConsultas);         

    }

    private String[][] obtenerMatrizLider() throws SQLException {        
        List<LiderVo> lideres = controller.listarLideres();        

        String matrizInfo[][] = new String[lideres.size()][5];
        for (int i = 0; i < lideres.size(); i++) {
            matrizInfo[i][0] = lideres.get(i).getIdLider() + "";
            matrizInfo[i][1] = lideres.get(i).getNombre() + "";
            matrizInfo[i][2] = lideres.get(i).getPrimerApellido() + "";
            matrizInfo[i][3] = lideres.get(i).getCiudadResidencia() + "";            
        }
        return matrizInfo;
    }
    
    
    
    private void construirTablaProyectos() throws SQLException {
        String titulos[] = {"ID_Proyecto", "Constructora", "Numero_Habitaciones", "Ciudad"};
        String informacionProyecto[][] = obtenerMatrizProyecto();        
        jTableConsultas = new JTable(informacionProyecto,titulos);
        jScrollPaneConsultas.setViewportView(jTableConsultas);         

    }

    private String[][] obtenerMatrizProyecto() throws SQLException {        
        List<ProyectoVo> proyectos = controller.listarProyectos();        

        String matrizInfo[][] = new String[proyectos.size()][5];
        for (int i = 0; i < proyectos.size(); i++) {
            matrizInfo[i][0] = proyectos.get(i).getIdProyecto()+ "";
            matrizInfo[i][1] = proyectos.get(i).getConstructora() + "";
            matrizInfo[i][2] = proyectos.get(i).getNumeroHabitaciones() + "";
            matrizInfo[i][3] = proyectos.get(i).getCiudad() + "";            
        }
        return matrizInfo;
    }
    
    
    private void construirTablaComprasProveedor() throws SQLException {
        String titulos[] = {"ID_Compra", "Proveedor", "Constructora", "Banco_Vinculado", "Ciudad"};
        String informacionProyecto[][] = obtenerMatrizComprasProveedor();        
        jTableConsultas = new JTable(informacionProyecto,titulos);
        jScrollPaneConsultas.setViewportView(jTableConsultas);         

    }

    private String[][] obtenerMatrizComprasProveedor() throws SQLException {        
        List<ComprasProveedorVo> compras = controller.listarComprasProveedor();        

        String matrizInfo[][] = new String[compras.size()][5];
        for (int i = 0; i < compras.size(); i++) {
            matrizInfo[i][0] = compras.get(i).getIdCompra()+ "";
            matrizInfo[i][1] = compras.get(i).getProveedor() + "";
            matrizInfo[i][2] = compras.get(i).getConstructora() + "";
            matrizInfo[i][3] = compras.get(i).getBancoVinculado() + "";            
            matrizInfo[i][4] = compras.get(i).getCiudad() + "";            
        }
        return matrizInfo;
    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VistaInformesReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VistaInformesReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VistaInformesReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VistaInformesReto4.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VistaInformesReto4().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPaneConsultas;
    // End of variables declaration//GEN-END:variables
}
